- name: This sets up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/euran-jenkins.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
  - name: "Install httpd and php packages"
    package:
        name:
          - "httpd"
          - "php"
        state: present
  - name: "copy code from GitHub"
    get_url:
        url: https://www.shubhammishra.in
        dest: "/var/www/html/index.php"
  - name: "Start httpd services"
    service:
        name: httpd
        state: started
  - name: Yum Install Packages
    yum: name={{item}} state=latest
    with_items:
       - wget
  - name: terraform install
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
